routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home');
});

Route::resource('summaries', 'SummaryController');
Route::resource('diets', 'DietController');
Route::resource('exercises', 'ExerciseController');
Route::resource('stressreliefs', 'StressReliefController');
Route::resource('goals', 'GoalController');

app/Diet.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

use DB;

class Diet extends Model
{

    public static function getAll(){
        $data = DB::table('diets')->orderBy('id', 'asc')->get();
        return $data;
    }

    public static function add($data){
        DB::table('diets')->insert($data);
        return $data;
    }

    protected $fillable = [
        'item',
        'type',
        'quantity'
    ];
}

app/Http/Controllers/DietController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;

use App\User;

use App\Diet;

use Validator;

class DietController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = Diet::getAll();
        $water_count = 0;
        $fruit_count = 0;
        $veggie_count = 0;
        
        foreach ($data as $item) {
            if ($item->type === 'Water') {
                $num = intval($item->quantity);
                $water_count = ($water_count + $num) * 8;
            } elseif ($item->type === 'Fruit') {
                $num = intval($item->quantity);
                $fruit_count = $fruit_count + $num;
            } elseif ($item->type === 'Vegetable') {
                $num = intval($item->quantity);
                $veggie_count = $veggie_count + $num;
            }
        }

        return view('diets.index', compact('water_count', 'fruit_count', 'veggie_count'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('diets.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'item'=>'required',
            'type'=>'required',
            'quantity'=>'required'
        ]);

        if ($validator->fails()) {
            return redirect('diets.create')
                    ->withErrors($validator)
                    ->withInput();
        } 

        else {
            Diet::add([
                'item' => $request->get('item'),
                'type' => $request->get('type'),
                'quantity' => $request->get('quantity')
            ]);
            
            return redirect('diets')->with('success', 'Entry saved!');
        }        
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/diets/create.blade.php
@extends('layout')

@section('title')
Diet
@stop

@section('content')
<div class="row">
  <div class="col-3">
    <div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
      <a class="nav-link active" id="v-pills-diet-tab" data-toggle="pill" href="#v-pills-diet" role="tab" aria-controls="v-pills-diet" aria-selected="true">Diet Summary</a>
      <a class="nav-link" id="v-pills-add-tab" data-toggle="pill" href="#v-pills-add" role="tab" aria-controls="v-pills-add" aria-selected="false">Add</a>
    </div>
  </div>
  <div class="col-9">
    <div class="tab-content" id="v-pills-tabContent">
      <div class="tab-pane fade show active" id="v-pills-diet" role="tabpanel" aria-labelledby="v-pills-diet-tab">
      <div class="row">
        <!-- Cards -->
        <div class="col-md-4">
          <div class="card text-white bg-primary mb-3" style="max-width: 18rem;">
            <div class="card-header">hydration</div>
            <div class="card-body">
              <h5 class="card-title">Total water (oz):</h5>
              <p class="card-text">
                <span class="display-2">32</span>
              </p>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="card text-white bg-danger mb-3" style="max-width: 18rem;">
            <div class="card-header">fruit</div>
            <div class="card-body">
              <h5 class="card-title">Total fruit:</h5>
              <p class="card-text">
                <span class="display-2">1</span>
              </p>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="card text-white bg-info mb-3" style="max-width: 18rem;">
            <div class="card-header">vegetables</div>
            <div class="card-body">
              <h5 class="card-title">Total vegetables:</h5>
              <p class="card-text">
                <span class="display-2">6</span>
              </p>
            </div>
          </div>
        </div>
      </div>
      <!-- End of Cards -->
      </div>
      hello
      <div class="tab-pane fade" id="v-pills-add" role="tabpanel" aria-labelledby="v-pills-add-tab">
        <!-- Form -->
        <p class="lead">
          Add fruits, vegetables, and hydration
        </p>
        <hr>
        <form method="POST" action="{{ route('diets.store') }}">
        @csrf
          <div class="form-group">
            <label for="item">Item</label>
            <input type="text" class="form-control" id="item">
          </div>
          <div class="form-group">
            <label for="type">Select type</label>
            <select class="form-control" id="type">
              <option>Fruit</option>
              <option>Vegetable</option>
              <option>Water</option>
            </select>
          </div>
          <div class="form-group">
            <label for="quantity">Select quantity (1 serving = 8oz of water)</label>
            <input type="text" class="form-control" id="quantity">
          </div>
          <button type="submit" class="btn btn-danger">Add</button>
        </form>
        <!-- End Form -->
      </div>
    </div>
  </div>
</div>
@stop

resources/views/diets/edit.blade.php
@extends('layout')

@section('title')
Diet
@stop

@section('content')
<div class="row">
  <div class="col-3">
    <div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
      <a class="nav-link active" id="v-pills-diet-tab" data-toggle="pill" href="#v-pills-diet" role="tab" aria-controls="v-pills-diet" aria-selected="true">Diet Summary</a>
      <a class="nav-link" id="v-pills-add-tab" data-toggle="pill" href="#v-pills-add" role="tab" aria-controls="v-pills-add" aria-selected="false">Add</a>
    </div>
  </div>
  <div class="col-9">
    <div class="tab-content" id="v-pills-tabContent">
      <div class="tab-pane fade show active" id="v-pills-diet" role="tabpanel" aria-labelledby="v-pills-diet-tab">
      <div class="row">
        <!-- Cards -->
        <div class="col-md-4">
          <div class="card text-white bg-primary mb-3" style="max-width: 18rem;">
            <div class="card-header">hydration</div>
            <div class="card-body">
              <h5 class="card-title">Total water (oz):</h5>
              <p class="card-text">
                <span class="display-2">{{{ $water_count }}}</span>
              </p>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="card text-white bg-danger mb-3" style="max-width: 18rem;">
            <div class="card-header">fruit</div>
            <div class="card-body">
              <h5 class="card-title">Total fruit:</h5>
              <p class="card-text">
                <span class="display-2">{{{ $fruit_count }}}</span>
              </p>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="card text-white bg-info mb-3" style="max-width: 18rem;">
            <div class="card-header">vegetables</div>
            <div class="card-body">
              <h5 class="card-title">Total vegetables:</h5>
              <p class="card-text">
                <span class="display-2">{{{ $veggie_count }}}</span>
              </p>
            </div>
          </div>
        </div>
      </div>
      <!-- End of Cards -->
      </div>
      <div class="tab-pane fade" id="v-pills-add" role="tabpanel" aria-labelledby="v-pills-add-tab">
        <!-- Form -->
        <p class="lead">
          Add fruits, vegetables, and hydration
        </p>
        <hr>
        <form method="POST" action="{{ route('diets.store') }}">
        @csrf
          <div class="form-group">
            <label for="item">Item</label>
            <input type="text" class="form-control" id="item" name="item">
          </div>
          <div class="form-group">
            <label for="type">Select type</label>
            <select class="form-control" id="type" name="type">
              <option>Fruit</option>
              <option>Vegetable</option>
              <option>Water</option>
            </select>
          </div>
          <div class="form-group">
            <label for="quantity">Select quantity (1 serving = 8oz of water)</label>
            <input type="text" class="form-control" id="quantity" name="quantity">
          </div>
          <button type="submit" class="btn btn-danger">Add</button>
        </form>
        <!-- End Form -->
      </div>
    </div>
  </div>
</div>
@stop

resources/views/diets/index.blade.php
@extends('layout')

@section('title')
Diet
@stop

@section('content')
<div class="row">
  <div class="col-3">
    <div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
      <a class="nav-link active" id="v-pills-diet-tab" data-toggle="pill" href="#v-pills-diet" role="tab" aria-controls="v-pills-diet" aria-selected="true">Diet Summary</a>
      <a class="nav-link" id="v-pills-add-tab" data-toggle="pill" href="#v-pills-add" role="tab" aria-controls="v-pills-add" aria-selected="false">Add</a>
    </div>
  </div>
  <div class="col-9">
    <div class="tab-content" id="v-pills-tabContent">
      <div class="tab-pane fade show active" id="v-pills-diet" role="tabpanel" aria-labelledby="v-pills-diet-tab">
      <div class="row">
        <!-- Cards -->
        <div class="col-md-4">
          <div class="card text-white bg-primary mb-3" style="max-width: 18rem;">
            <div class="card-header">hydration</div>
            <div class="card-body">
              <h5 class="card-title">Total water (oz):</h5>
              <p class="card-text">
                <span class="display-2">{{{ $water_count }}}</span>
              </p>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="card text-white bg-danger mb-3" style="max-width: 18rem;">
            <div class="card-header">fruit</div>
            <div class="card-body">
              <h5 class="card-title">Total fruit:</h5>
              <p class="card-text">
                <span class="display-2">{{{ $fruit_count }}}</span>
              </p>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="card text-white bg-info mb-3" style="max-width: 18rem;">
            <div class="card-header">vegetables</div>
            <div class="card-body">
              <h5 class="card-title">Total vegetables:</h5>
              <p class="card-text">
                <span class="display-2">{{{ $veggie_count }}}</span>
              </p>
            </div>
          </div>
        </div>
      </div>
      <!-- End of Cards -->
      </div>
      <div class="tab-pane fade" id="v-pills-add" role="tabpanel" aria-labelledby="v-pills-add-tab">
        <!-- Form -->
        <p class="lead">
          Add fruits, vegetables, and hydration
        </p>
        <hr>
        <form method="POST" action="{{ route('diets.store') }}">
        @csrf
          <div class="form-group">
            <label for="item">Item</label>
            <input type="text" class="form-control" id="item" name="item">
          </div>
          <div class="form-group">
            <label for="type">Select type</label>
            <select class="form-control" id="type" name="type">
              <option>Fruit</option>
              <option>Vegetable</option>
              <option>Water</option>
            </select>
          </div>
          <div class="form-group">
            <label for="quantity">Select quantity (1 serving = 8oz of water)</label>
            <input type="text" class="form-control" id="quantity" name="quantity">
          </div>
          <button type="submit" class="btn btn-danger">Add</button>
        </form>
        <!-- End Form -->
      </div>
    </div>
  </div>
</div>
@stop