routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home');
});

Route::resource('summaries', 'SummaryController');
Route::resource('diets', 'DietController');
Route::resource('exercises', 'ExerciseController');
Route::resource('stressreliefs', 'StressReliefController');
Route::resource('goals', 'GoalController');

app/Stress_Relief.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

use DB;

class Stress_Relief extends Model
{
    public static function getAll(){
        $data=DB::table('stressreliefs')->orderBy('id', 'asc')->get();
        return $data;
    }

    public static function add($data){
        DB::table('stressreliefs')->insert($data);
        return $data;
    }

    protected $fillable = [
        'activity',
        'type',
        'duration'
    ];
}

app/Http/Controllers/StressReliefController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Stress_Relief;

use Validator;

class StressReliefController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = Stress_Relief::getAll();
        $mindful_count = 0;
        $connection_count = 0;
        $mental_count = 0;

        foreach ($data as $activity) {
            if ($activity->type === 'Mediation' || 
                $activity->type === 'Free time' || 
                $activity->type === 'Screen-free') {
                $num = intval($activity->duration);
                $mindful_count = ($mindful_count + $num) / 60;
                $mindful_count = round($mindful_count, 2);
            } elseif ($activity->type === 'Family & Friends' ||
                    $activity->type === 'Hobby') {
                $num = intval($activity->duration);
                $connection_count = ($connection_count + $num) / 60;
                $connection_count = round($connection_count, 2);
            } elseif ($activity->type === 'Therapy') {
                $num = intval($activity->duration);
                $mental_count = ($mental_count + $num) / 60;
                $mental_count = round($mental_count, 2);
            }
        }

        return view('stressreliefs.index', compact('mindful_count', 'connection_count', 'mental_count'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('stressreliefs.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'activity'=>'required',
            'type'=>'required',
            'duration'=>'required'
        ]);

        if ($validator->fails()) {
            return redirect('stressreliefs.create')
                    ->withErrors($validator)
                    ->withInput();
        } 

        else {
            Stress_Relief::add([
                'activity' => $request->get('activity'),
                'type' => $request->get('type'),
                'duration' => $request->get('duration')
            ]);
            
            return redirect('stressreliefs')->with('success', 'Entry saved!');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/stressreliefs/create.blade.php
@extends('layout')

@section('title')
Stress Relief
@stop

@section('content')
<div class="row">
  <div class="col-3">
    <div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
      <a class="nav-link active" id="v-pills-stress-tab" data-toggle="pill" href="#v-pills-stress" role="tab" aria-controls="v-pills-stress" aria-selected="true">Stress Relief Summary</a>
      <a class="nav-link" id="v-pills-add-tab" data-toggle="pill" href="#v-pills-add" role="tab" aria-controls="v-pills-add" aria-selected="false">Add</a>
    </div>
  </div>
  <div class="col-9">
    <div class="tab-content" id="v-pills-tabContent">
      <div class="tab-pane fade show active" id="v-pills-stress" role="tabpanel" aria-labelledby="v-pills-stress-tab">
      <div class="row">
        <!-- Cards -->
        <div class="col-md-4">
          <div class="card text-white bg-primary mb-3" style="max-width: 18rem;">
            <div class="card-header">mindfulness & meditation</div>
            <div class="card-body">
              <h5 class="card-title">Mindfulness hours:</h5>
              <p class="card-text">
                <span class="display-2">2</span>
              </p>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="card text-white bg-danger mb-3" style="max-width: 18rem;">
            <div class="card-header">face-to-face connection</div>
            <div class="card-body">
              <h5 class="card-title">Connection hours:</h5>
              <p class="card-text">
                <span class="display-2">5</span>
              </p>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="card text-white bg-info mb-3" style="max-width: 18rem;">
            <div class="card-header">mental health</div>
            <div class="card-body">
              <h5 class="card-title">Mental health hours:</h5>
              <p class="card-text">
                <span class="display-2">4</span>
              </p>
            </div>
          </div>
        </div>
      </div>
      <!-- End of Cards -->
      </div>
      <div class="tab-pane fade" id="v-pills-add" role="tabpanel" aria-labelledby="v-pills-add-tab">
        <!-- Form -->
        <p class="lead">
          Add activity
        </p>
        <hr>
        <form method="POST" action="{{ route('stressreliefs.store') }}">
        @csrf
          <div class="form-group">
            <label for="activity">Activity</label>
            <input type="text" class="form-control" id="activity" name="activity">
          </div>

          <div class="form-group">
            <label for="type">Select type</label>
            <select class="form-control" id="type" name="type">
            <option>Mediation</option>
              <option>Free time</option>
              <option>Screen-free</option>
              <option>Family & Friends</option>
              <option>Hobby</option>
              <option>Therapy</option>
            </select>
          </div>

          <div class="form-group">
            <label for="duration">Duration (in min)</label>
            <input type="text" class="form-control" id="duration" name="duration">
          </div>
          <button type="submit" class="btn btn-danger">Add</button>
        </form>
        <!-- End Form -->
      </div>
    </div>
  </div>
</div>
@stop

resources/views/stressreliefs/index.blade.php
@extends('layout')

@section('title')
Stress Relief
@stop

@section('content')
<div class="row">
  <div class="col-3">
    <div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
      <a class="nav-link active" id="v-pills-stress-tab" data-toggle="pill" href="#v-pills-stress" role="tab" aria-controls="v-pills-stress" aria-selected="true">Stress Relief Summary</a>
      <a class="nav-link" id="v-pills-add-tab" data-toggle="pill" href="#v-pills-add" role="tab" aria-controls="v-pills-add" aria-selected="false">Add</a>
    </div>
  </div>
  <div class="col-9">
    <div class="tab-content" id="v-pills-tabContent">
      <div class="tab-pane fade show active" id="v-pills-stress" role="tabpanel" aria-labelledby="v-pills-stress-tab">
      <div class="row">
        <!-- Cards -->
        <div class="col-md-4">
          <div class="card text-white bg-primary mb-3" style="max-width: 18rem;">
            <div class="card-header">mindfulness & meditation</div>
            <div class="card-body">
              <h5 class="card-title">Mindfulness hours:</h5>
              <p class="card-text">
                <span class="display-2">{{{ $mindful_count }}}</span>
              </p>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="card text-white bg-danger mb-3" style="max-width: 18rem;">
            <div class="card-header">face-to-face connection</div>
            <div class="card-body">
              <h5 class="card-title">Connection hours:</h5>
              <p class="card-text">
                <span class="display-2">{{{ $connection_count }}}</span>
              </p>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="card text-white bg-info mb-3" style="max-width: 18rem;">
            <div class="card-header">mental health</div>
            <div class="card-body">
              <h5 class="card-title">Mental health hours:</h5>
              <p class="card-text">
                <span class="display-2">{{{ $mental_count }}}</span>
              </p>
            </div>
          </div>
        </div>
      </div>
      <!-- End of Cards -->
      </div>
      <div class="tab-pane fade" id="v-pills-add" role="tabpanel" aria-labelledby="v-pills-add-tab">
        <!-- Form -->
        <p class="lead">
          Add activity
        </p>
        <hr>
        <form method="POST" action="{{ route('stressreliefs.store') }}">
        @csrf
          <div class="form-group">
            <label for="activity">Activity</label>
            <input type="text" class="form-control" id="activity" name="activity">
          </div>

          <div class="form-group">
            <label for="type">Select type</label>
            <select class="form-control" id="type" name="type">
            <option>Mediation</option>
              <option>Free time</option>
              <option>Screen-free</option>
              <option>Family & Friends</option>
              <option>Hobby</option>
              <option>Therapy</option>
            </select>
          </div>

          <div class="form-group">
            <label for="duration">Duration (in min)</label>
            <input type="text" class="form-control" id="duration" name="duration">
          </div>
          <button type="submit" class="btn btn-danger">Add</button>
        </form>
        <!-- End Form -->
      </div>
    </div>
  </div>
</div>
@stop